./" 2008+ Copyright (c) Evgeniy Polyakov <zbr@ioremap.net>
./" All rights reserved.

.TH MAN 1 2013-07-10 "Linux" "Elliptics admin's guide"
.SH NAME
dnet_ioserv \- elliptics node.
.SH SYNOPSIS
.B dnet_ioserv \-c 
.I configuration_file 
.B [-mlh]
.P
.SH DESCRIPTION
.P
Run this command to start elliptics node.
.P
At start you should pass path to the configuration file of the server. Example of the configuration file you can find at
.I /usr/share/doc/elliptics/examples/ioserv.json. 
There are present all of the possible parameters with the detailed comments. 
.P
Some more information about elliptics configuring you can get in the project documentation http://doc.reverbrain.com.
.SH OPTIONS
.TP
.B \-m
Run under internal monitor.
.TP
.B \-l log
Log file.
.TP
.B \-h, \-\^\-help
Show help message and exit.
.SH EXAMPLES
dnet_ioserv -c some.config
.SH AUTHOR
Evgeniy Polyakov (zbr@ioremap.net)
.SH SEE ALSO
.P
.BR dnet_find (1),
.BR dnet_ioclient (1),
.BR dnet_recovery (1),
.BR eblob_index_info (1),
.BR eblob_merge (1),
.BR eblob_regex_iter (1).
.P
Complete documentation on project you can find at http://doc.reverbrain.com.
